from __future__ import annotations

from typing import Any, Protocol


class FinancialTools(Protocol):
    settings: Any

    def resolve_symbol(self, query: str, market: str | None = None) -> dict[str, Any]: ...

    def company_profile(self, ticker: str) -> dict[str, Any]: ...

    def company_financials(self, ticker: str) -> dict[str, Any]: ...

    def competitor_analysis(self, ticker: str) -> list[str]: ...

    def latest_news(self, ticker: str) -> list[dict[str, Any]]: ...

    def latest_earnings(self, ticker: str) -> dict[str, Any]: ...

    def search_documents(self, query: str) -> list[Any]: ...

    def market_snapshot(self, ticker: str) -> dict[str, Any]: ...

    def price_history(self, ticker: str, horizon: str) -> dict[str, Any]: ...

    def market_status(self) -> dict[str, Any]: ...

    def buying_power(self) -> float: ...
